import { useState, useCallback } from "react";
import type { GuardRule, PropertyData, RiskLevel } from "../types";
import { API_BASE_URL } from "../config";

export interface UseGuardRulesReturn {
  rules: GuardRule[];
  generating: string | null;
  modalRule: GuardRule | null;
  error: string | null;
  generateRule: (
    property: PropertyData,
    resourceUrl: string,
    resourceType: string,
  ) => Promise<void>;
  addToCollection: (rule: GuardRule) => void;
  removeFromCollection: (ruleName: string) => void;
  openModal: (rule: GuardRule) => void;
  closeModal: () => void;
  clearError: () => void;
  downloadGuardFile: () => void;
  downloadTestTemplates: () => void;
}

function triggerDownload(content: string, filename: string) {
  const blob = new Blob([content], { type: "text/plain" });
  const url = URL.createObjectURL(blob);
  const a = document.createElement("a");
  a.href = url;
  a.download = filename;
  a.click();
  URL.revokeObjectURL(url);
}

/** Indent each line of a multi-line string by `spaces` spaces. */
function indent(text: string, spaces: number): string {
  const pad = " ".repeat(spaces);
  return text
    .split("\n")
    .map((line) => pad + line)
    .join("\n");
}

export function useGuardRules(): UseGuardRulesReturn {
  const [rulesMap, setRulesMap] = useState<Map<string, GuardRule>>(new Map());
  const [generating, setGenerating] = useState<string | null>(null);
  const [modalRule, setModalRule] = useState<GuardRule | null>(null);
  const [error, setError] = useState<string | null>(null);

  const rules = Array.from(rulesMap.values());

  const generateRule = useCallback(
    async (property: PropertyData, resourceUrl: string, resourceType: string) => {
      setGenerating(property.name);
      setError(null);

      const controller = new AbortController();
      const timeout = setTimeout(() => controller.abort(), 30_000);

      try {
        const resp = await fetch(`${API_BASE_URL}/guard-rules`, {
          method: "POST",
          headers: { "Content-Type": "application/json" },
          signal: controller.signal,
          body: JSON.stringify({
            resourceType,
            resourceUrl,
            propertyName: property.name,
            riskLevel: property.risk_level,
            securityImplication: property.security_impact,
            recommendation: property.recommendation,
          }),
        });

        if (!resp.ok) {
          const detail = await resp.json().catch(() => ({}));
          throw new Error(detail.detail || `HTTP ${resp.status}`);
        }

        const data = await resp.json();
        const rule: GuardRule = {
          ...data,
          riskLevel: property.risk_level,
        };

        setModalRule(rule);
      } catch (err: unknown) {
        const msg =
          err instanceof DOMException && err.name === "AbortError"
            ? "Guard rule generation timed out (30s)"
            : (err as Error).message;
        setError(msg);
      } finally {
        clearTimeout(timeout);
        setGenerating(null);
      }
    },
    [],
  );

  const addToCollection = useCallback((rule: GuardRule) => {
    setRulesMap((prev) => new Map(prev).set(rule.propertyName, rule));
  }, []);

  const removeFromCollection = useCallback((ruleName: string) => {
    setRulesMap((prev) => {
      const next = new Map(prev);
      for (const [key, val] of next) {
        if (val.ruleName === ruleName) {
          next.delete(key);
          break;
        }
      }
      return next;
    });
  }, []);

  const openModal = useCallback((rule: GuardRule) => setModalRule(rule), []);
  const closeModal = useCallback(() => setModalRule(null), []);
  const clearError = useCallback(() => setError(null), []);

  const downloadGuardFile = useCallback(() => {
    if (rules.length === 0) return;
    const timestamp = new Date().toISOString();
    const resourceType = rules[0]?.resourceType ?? "Unknown";
    const header = `# ============================================================\n# CFN Guard Rules — Generated by CloudFormation Security Analyzer\n# Resource: ${resourceType}\n# Generated: ${timestamp}\n# ============================================================\n`;
    const body = rules
      .map(
        (r) =>
          `\n# Rule: ${r.ruleName}\n# Risk: ${r.riskLevel}\n# Description: ${r.description}\n${r.guardRule}\n`,
      )
      .join("\n");
    triggerDownload(header + body, "cfn-guard-rules.guard");
  }, [rules]);

  const downloadTestTemplates = useCallback(() => {
    if (rules.length === 0) return;
    const entries = rules.flatMap((r) => [
      `- name: "${r.ruleName} - PASS"\n  input:\n${indent(r.passTemplate, 4)}\n  expectations:\n    rules:\n      ${r.ruleName}: PASS\n`,
      `- name: "${r.ruleName} - FAIL"\n  input:\n${indent(r.failTemplate, 4)}\n  expectations:\n    rules:\n      ${r.ruleName}: FAIL\n`,
    ]);
    triggerDownload(entries.join("\n"), "cfn-guard-tests.yaml");
  }, [rules]);

  return {
    rules,
    generating,
    modalRule,
    error,
    generateRule,
    addToCollection,
    removeFromCollection,
    openModal,
    closeModal,
    clearError,
    downloadGuardFile,
    downloadTestTemplates,
  };
}
